### ISSUE TITLE
Add example data set

### ISSUE THREAD

**Issue by sdmiller** [sdmiller/cpu_tsdf#14]
I've been away from Stanford for a couple years, and as such haven't used this code much. So I'm afraid my current OSX machine doesn't have any example datasets of point clouds + poses to help people get started.

If any of you happen to have something laying around -- maybe a ~10 frame example -- I'd love to host it and provide a tutorial to accompany this. Let me know!

**Comment by AbyssGaze** [comment]
I have captured some data for object reconstruction. The point clouds are translated in the world coordinate .

**Comment by JiayongLF** [comment]
@vidstige Hi, I am a student and I am using this code. I want to see the effect so could you please sent a copy of the data to me? Thank you very much. This is my email address: pengjiayong2013@gmail.com.

**Comment by lyziew** [comment]
@vidstige Hi,  I try to run this code use my data, but  I when I trun the tsdf  to mesh, I always get a message that:
[pcl::io::savePLYFile] Input point cloud has no data!
Cloud you sent a copy of your test data to me, then i can check my mistake, hope for your help
Email address: liyunlllyyy@sina.com

**Comment by vidstige** [comment]
@lyziew I pushed the dataset to a repo over here: https://github.com/vidstige/dataset_samuel

**Comment by lyziew** [comment]
@vidstige thank you very much, I have found the mistake :)

**Comment by vidstige** [comment]
@lyziew glad it helped! :)

**Comment by sdmiller** [comment]
I finally hopped on a Linux machine and added a compatible dataset -- see README for details.
