### ISSUE TITLE
PCD with relative Pose TXT file problems

### ISSUE THREAD

**Issue by m4nh** [sdmiller/cpu_tsdf#16]
If for some reason some PCD file or some TXT file is missing in "integrate" program loading process fail to map each PCD file with corresponding TXT. For example if i load correctly this list:

1.pcd -> 1.txt
2.pcd -> 2.txt
3.pcd -> 3.txt
5.pcd -> 4.txt

and "2.pcd" is missing, i load instead:

1.pcd -> 1.txt
3.pcd -> 2.txt
4.pcd -> 3.txt

**Comment by sdmiller** [comment]
Good catch! I recall my personal variant of the ./integrate script was explicitly checking for prefixes being equal, rather than committing to blind ordering. I'll update this one to do the same.

**Comment by sdmiller** [comment]
@m4nh https://github.com/sdmiller/cpu_tsdf/pull/17 should fix it! Would appreciate it if you could take a glance, see if it solves your problem, and hit "Merge" if so.

Cheers
-Stephen

**Comment by m4nh** [comment]
@sdmiller it works!
