### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file “Debug\cpu_tsdf.lib”

### ISSUE THREAD

**Issue by rangerlcy** [sdmiller/cpu_tsdf#20]
Hi, I'm a newer in pcl. I try compile the whole project by using vs2013 after cmake and build. But I get a link error. 

I go to Debug directory and just see cpu_tsdf.dll. No cpu_tsdf.lib file. Why?

By the way, I have configured PCL development environment correctly.

**Comment by sdmiller** [comment]
Hi @rangerlcy,

I'm afraid I don't have a ton of experience with Windows in general, or Visual Studio in particular. I'm guessing my CMakeList.txt isn't currently playing nicely with VS -- or if it is, it's just by sheer luck / the portability of CMake.

From what little I know about the Windows filesystem, I think this is a problem of telling CMake to properly build export libraries? https://cmake.org/Wiki/BuildingWinDLL has some information here. I don't currently have a Windows machine to test, but maybe I can hop on a VM in a bit and try it out.

**Comment by rangerlcy** [comment]
Thank you for your reply. I have implemented cpu version TSDF by myself.

**Comment by JiayongLF** [comment]
Hi rangerlcy, could you tell me how to compile the whole project by using VS2013 after cmake and build. I am problem with this recently. Thank you very much.

**Comment by JiayongLF** [comment]
@rangerlcy Hi rangerlcy, could you tell me how to compile the whole project by using VS2013 after cmake and build. I am problem with this recently. Thank you very much.
