### ISSUE TITLE
Question about tsdf

### ISSUE THREAD

**Issue by ghost** [sdmiller/cpu_tsdf#25]
Hi,

Is what I can calculate tsdf for a cloud of points not for depth images ?
You can help me with an idea

Thank you for your help.

**Comment by sdmiller** [comment]
Hi @PlayerUsr,

The two are basically interchangable. In this case, an organized point cloud is basically a depth image + knowledge of camera intrinsics. If you have a depth image D(u,v) = z, and you know your sensor has focal lengths (fx,fy) and center pixels (cx,cy), you can create a point cloud via:

```
pcl::PointCloud<pcl::PointXYZ> cloud (width, height);
for (int u = 0; u < width; ++u) {
  for (int v = 0; v < height; ++v) {
    pcl::PointXYZ &pt = cloud(u,v);
    if (/* however you check that there is no depth data for D(u,v) goes here */) {
      pt.x = pt.y = pt.z = std::numeric_limits<float>::quiet_NaN();
   }
   else {
     pt.z = D(u,v);
     pt.x = pt.z / fx * (u - cx);
     pt.y = pt.z / fy * (v - cy); 
   }
 }
}
```

**Comment by PlayerUsr** [comment]
Thank you very much for your answer.

But i try to change:
// CUDA kernel function to integrate a TSDF voxel volume given **_depth images_**
to
// CUDA kernel function to integrate a TSDF voxel volume given _**points cloud**_

==> The input of TDF is a points cloud **not**  depth images.

You can help me with an idea

**Comment by sdmiller** [comment]
Algorithmically, the input can be either. I guess what I'd need to know is what sort of CUDA functions you are using here -- this library is entirely in the CPU. PCL's point cloud type just happens to be a convenient wrapper for a depth image with known intrinsics, but it certainly isn't the only way. For instance, I believe the pcl::KinfuTracker class actually operates on depth images instead.
