### ISSUE TITLE
Coordinate frame of point cloud expected

### ISSUE THREAD

**Issue by JackGitHub131** [sdmiller/cpu_tsdf#28]
I am noticing if I use 1 cloud (with min weight set to 1), it seems like the cloud is cropped and I dont always get the full data. If I set the min sensor bounds to -5.0, then I can get a little bit of extra data but it is noisy. What is the format of the point cloud expected? 

I am using RealSense R200 sensors which have (from the cameras perspective) Z pointing out towards the scene, X pointing right and Y pointing down.

**Comment by sdmiller** [comment]
Hi @JackGitHub131 ,

Would it be possible to send a cloud as an example? Data is expected in the format you mentioned; but it is possible that the focal lengths are not properly set. This is for a few reasons:
1) If the focal length is off, raytracing may start to systematically fail for more cases, and you'll have a perceptively smaller result
2) We use Frustum Culling so only voxels that ought to be in the camera's FOV are considered. Until recently this was hard coded to be a more permissive version of the connect. I've updated it here to work dynamically based on focal length: https://github.com/sdmiller/cpu_tsdf/pull/29

It could also simply be that the TSDF itself isn't large enough? What size parameters are you initializing the volume with?
