### ISSUE TITLE
Example data for tests

### ISSUE THREAD

**Issue by rachillesf** [sdmiller/cpu_tsdf#31]
Hi, 

first of all, thanks for your work!

It would be possible for you to share a sample folder with some data for testing, eg. pcd files with the .txt poses?

Thanks

**Comment by sdmiller** [comment]
Hi @rachillesf,

I'm afraid I haven't run this code in quite some time (and OSX High Sierra seems to not like VTK enough to let me recompile PCL)! I can try and dig up some pcd files on my Linux box in a bit.

**Comment by rachillesf** [comment]
Thank you very much! Just the pcd files with the poses would be awesome!

**Comment by sdmiller** [comment]
Uploaded sample data to http://s3.sdavidmiller.com/data/cpu_tsdf_sample_data.zip . Thanks to my old colleagues Sungjoon, Qian-Yi, and Vladlen for the dataset!

**Comment by rachillesf** [comment]
Thanks! Just tested, it worked nicely!

**Comment by E-BAO** [comment]
Hi @rachillesf,
The sample data seems to be expired. Could you please update the link of  http://s3.sdavidmiller.com/data/cpu_tsdf_sample_data.zip  ? It's hard to understand the program without sample data. Thanks!!!

**Comment by sdmiller** [comment]
Hey @E-BAO, no idea why that link stopped working, will investigate asap!

**Comment by sdmiller** [comment]
@E-BAO Seems the redirect subdomain is busted for some reason; this should work: 
https://s3-us-west-1.amazonaws.com/s3.sdavidmiller.com/data/cpu_tsdf_sample_data.zip

**Comment by E-BAO** [comment]
@rachillesf ,
Thanks for the quick update! It helps a lot!

**Comment by sdmiller** [comment]
No problem :). By the way, now that the subdomain is busted, I'm switching to a slightly shorter URL...so you'll want to use this one instead (will update the readme too):

http://sdavidmiller.s3.amazonaws.com/data/cpu_tsdf_sample_data.zip
