### ISSUE TITLE
How to get the pose.txt....

### ISSUE THREAD

**Issue by DQ0408** [sdmiller/cpu_tsdf#34]
Hi, I am new to SLAM,I have the data from RGBD https://vision.in.tum.de/data/datasets/rgbd-dataset
this dataset provides grandtruth, what should i do to convert grandtruth.txt to pose.txt?THX...

**Comment by sdmiller** [comment]
Hi @DQ0408, welcome to SLAM :).

According to https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats, the groundtruth text file seems to have lines in the format:

"The format of each line is 'timestamp tx ty tz qx qy qz qw'"

Where the timestamp should be (hopefully) in the same format as the title of the PNGs and depth maps.

To convert from tx ty tz qx qy qz qw to a 4x4 pose matrix, the easiest thing would be to use Eigen:

```
Eigen::Matrix4f poseMat = (Eigen::Translation3f(tx,ty,tz) * Eigen::Quaternionf(qw, qx, qy, qz)).matrix();
```
(off the top of my head so please excuse typos!)

It's possible that the RGBD dataset is assuming a different coordinate frame than I am (x right, y down, z forward). If so, you'll either want to permute and negate the t[x,y,z] and q[x,y,z]s accordingly, or you'll want to figure out the effective coordinate transform matrix and use it to modify the pose mat.

For instance:
```
Eigen::Matrix4f coordTrans; 
coordTrans 
    <<  0,1,0,0
    << -1,0,0,0
    <<  0,0,1,0
    <<  0,0,0,1;
poseMat = coordTrans * poseMat * coordTrans.inv();
```

**Comment by DQ0408** [comment]
thank you！This problem has troubled me for a long time... I just learned the term Lie Algebra just now.Anyway, thank you very much!You are soooooo nice~
