### ISSUE TITLE
wrong include path

### ISSUE THREAD

**Issue by Janos95** [sdmiller/cpu_tsdf#35]
Is it possible that the include path in CPUTSDFConfig file ist wrong? The cmake file is setting CPUTSDF_INCLUDE_DIR  as @CMAKE_INSTALL_PREFIX@/include/cpu_tsdf. But
for example in your integrate script you are including #include <cpu_tsdf/tsdf_volume_octree.h> so this wont compile. To make everything work I think one hsould set CPUTSDF_INCLUDE_DIR to @CMAKE_INSTALL_PREFIX@/include.

**Comment by sdmiller** [comment]
Yup that seems absolutely right! Not sure how / when that config was created, but from the looks of it your change is correct.

Since I'm not currently on a machine that has PCL running, I can't really test this -- could you open a PR?

**Comment by sdmiller** [comment]
Solved by latest PR, thanks @Janos95 !
