### ISSUE TITLE
build with pcl 1.8.1 failure

### ISSUE THREAD

**Issue by xlla** [sdmiller/cpu_tsdf#45]
when I try build the code, the follow error occur:

mkdir build && cd build && cmake .. && make -j8
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Checking for module 'eigen3'
--   Found eigen3, version 3.3.4
-- Found eigen: /usr/include/eigen3  
-- Checking for module 'libopenni'
--   Found libopenni, version 1.5.4.0
-- Found openni: /usr/lib/libOpenNI.so  
-- Found libusb-1.0: /usr/include  
-- Checking for module 'flann'
--   Found flann, version 1.9.1
-- Found Flann: /usr/lib/x86_64-linux-gnu/libflann_cpp_s.a  
-- Found qhull: /usr/lib/x86_64-linux-gnu/libqhull.so  
-- Found PCL_COMMON: /usr/lib/x86_64-linux-gnu/libpcl_common.so  
-- Found PCL_OCTREE: /usr/lib/x86_64-linux-gnu/libpcl_octree.so  
-- Found PCL_IO: /usr/lib/x86_64-linux-gnu/libpcl_io.so  
-- Found PCL_KDTREE: /usr/lib/x86_64-linux-gnu/libpcl_kdtree.so  
-- Found PCL_SEARCH: /usr/lib/x86_64-linux-gnu/libpcl_search.so  
-- Found PCL_SAMPLE_CONSENSUS: /usr/lib/x86_64-linux-gnu/libpcl_sample_consensus.so  
-- Found PCL_FILTERS: /usr/lib/x86_64-linux-gnu/libpcl_filters.so  
-- Found PCL_2D: /usr/include/pcl-1.8  
-- Found PCL_GEOMETRY: /usr/include/pcl-1.8  
-- Found PCL_FEATURES: /usr/lib/x86_64-linux-gnu/libpcl_features.so  
-- Found PCL_ML: /usr/lib/x86_64-linux-gnu/libpcl_ml.so  
-- Found PCL_SEGMENTATION: /usr/lib/x86_64-linux-gnu/libpcl_segmentation.so  
-- Found PCL_VISUALIZATION: /usr/lib/x86_64-linux-gnu/libpcl_visualization.so  
-- Found PCL_SURFACE: /usr/lib/x86_64-linux-gnu/libpcl_surface.so  
-- Found PCL_REGISTRATION: /usr/lib/x86_64-linux-gnu/libpcl_registration.so  
-- Found PCL_KEYPOINTS: /usr/lib/x86_64-linux-gnu/libpcl_keypoints.so  
-- Found PCL_TRACKING: /usr/lib/x86_64-linux-gnu/libpcl_tracking.so  
-- Found PCL_RECOGNITION: /usr/lib/x86_64-linux-gnu/libpcl_recognition.so  
-- Found PCL_STEREO: /usr/lib/x86_64-linux-gnu/libpcl_stereo.so  
-- Found PCL_APPS: /usr/lib/x86_64-linux-gnu/libpcl_apps.so  
-- Found PCL_IN_HAND_SCANNER: /usr/include/pcl-1.8  
-- Found PCL_MODELER: /usr/include/pcl-1.8  
-- Found PCL_POINT_CLOUD_EDITOR: /usr/include/pcl-1.8  
-- Found PCL_OUTOFCORE: /usr/lib/x86_64-linux-gnu/libpcl_outofcore.so  
-- Found PCL_PEOPLE: /usr/lib/x86_64-linux-gnu/libpcl_people.so  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xlla/git/cpu_tsdf/build
Scanning dependencies of target get_intrinsics
Scanning dependencies of target cpu_tsdf
[  9%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/octree.cpp.o
[ 18%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o
[ 27%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/tsdf_interface.cpp.o
[ 36%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/tsdf_volume_octree.cpp.o
[ 45%] Building CXX object CMakeFiles/get_intrinsics.dir/src/prog/get_intrinsics.cpp.o
/home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp: In member function ‘void cpu_tsdf::MarchingCubesTSDFOctree::setInputTSDF(cpu_tsdf::TSDFVolumeOctree::ConstPtr)’:
/home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:3: error: ‘size_voxel_’ was not declared in this scope
   size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
   ^~~~~~~~~~~
/home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:3: note: suggested alternative: ‘size_x’
   size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
   ^~~~~~~~~~~
   size_x
/home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:18: error: ‘upper_boundary_’ was not declared in this scope
   size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
                  ^~~~~~~~~~~~~~~
/home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:36: error: ‘lower_boundary_’ was not declared in this scope
   size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
                                    ^~~~~~~~~~~~~~~
In file included from /home/xlla/git/cpu_tsdf/src/prog/get_intrinsics.cpp:42:0:
/usr/include/pcl-1.8/pcl/visualization/cloud_viewer.h:202:14: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
         std::auto_ptr<CloudViewer_impl> impl_;
              ^~~~~~~~
In file included from /usr/include/c++/7/memory:80:0,
                 from /usr/include/boost/config/no_tr1/memory.hpp:21,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/pcl-1.8/pcl/correspondence.h:45,
                 from /usr/include/pcl-1.8/pcl/visualization/pcl_visualizer.h:42,
                 from /usr/include/pcl-1.8/pcl/visualization/cloud_viewer.h:39,
                 from /home/xlla/git/cpu_tsdf/src/prog/get_intrinsics.cpp:42:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
CMakeFiles/cpu_tsdf.dir/build.make:134: recipe for target 'CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o' failed
make[2]: *** [CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/cpu_tsdf.dir/all' failed
make[1]: *** [CMakeFiles/cpu_tsdf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 54%] Linking CXX executable get_intrinsics
[ 54%] Built target get_intrinsics
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

if I comment that line, ... size_voxel_ ..., then it built.

**Comment by 0dmf0** [comment]
So, do you solve this question now ?
I also meet with this

**Comment by 0dmf0** [comment]
> when I try build the code, the follow error occur:
> 
> mkdir build && cd build && cmake .. && make -j8
> -- The C compiler identification is GNU 7.4.0
> -- The CXX compiler identification is GNU 7.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found OpenMP_C: -fopenmp (found version "4.5")
> -- Found OpenMP_CXX: -fopenmp (found version "4.5")
> -- Found OpenMP: TRUE (found version "4.5")
> -- Checking for module 'eigen3'
> -- Found eigen3, version 3.3.4
> -- Found eigen: /usr/include/eigen3
> -- Checking for module 'libopenni'
> -- Found libopenni, version 1.5.4.0
> -- Found openni: /usr/lib/libOpenNI.so
> -- Found libusb-1.0: /usr/include
> -- Checking for module 'flann'
> -- Found flann, version 1.9.1
> -- Found Flann: /usr/lib/x86_64-linux-gnu/libflann_cpp_s.a
> -- Found qhull: /usr/lib/x86_64-linux-gnu/libqhull.so
> -- Found PCL_COMMON: /usr/lib/x86_64-linux-gnu/libpcl_common.so
> -- Found PCL_OCTREE: /usr/lib/x86_64-linux-gnu/libpcl_octree.so
> -- Found PCL_IO: /usr/lib/x86_64-linux-gnu/libpcl_io.so
> -- Found PCL_KDTREE: /usr/lib/x86_64-linux-gnu/libpcl_kdtree.so
> -- Found PCL_SEARCH: /usr/lib/x86_64-linux-gnu/libpcl_search.so
> -- Found PCL_SAMPLE_CONSENSUS: /usr/lib/x86_64-linux-gnu/libpcl_sample_consensus.so
> -- Found PCL_FILTERS: /usr/lib/x86_64-linux-gnu/libpcl_filters.so
> -- Found PCL_2D: /usr/include/pcl-1.8
> -- Found PCL_GEOMETRY: /usr/include/pcl-1.8
> -- Found PCL_FEATURES: /usr/lib/x86_64-linux-gnu/libpcl_features.so
> -- Found PCL_ML: /usr/lib/x86_64-linux-gnu/libpcl_ml.so
> -- Found PCL_SEGMENTATION: /usr/lib/x86_64-linux-gnu/libpcl_segmentation.so
> -- Found PCL_VISUALIZATION: /usr/lib/x86_64-linux-gnu/libpcl_visualization.so
> -- Found PCL_SURFACE: /usr/lib/x86_64-linux-gnu/libpcl_surface.so
> -- Found PCL_REGISTRATION: /usr/lib/x86_64-linux-gnu/libpcl_registration.so
> -- Found PCL_KEYPOINTS: /usr/lib/x86_64-linux-gnu/libpcl_keypoints.so
> -- Found PCL_TRACKING: /usr/lib/x86_64-linux-gnu/libpcl_tracking.so
> -- Found PCL_RECOGNITION: /usr/lib/x86_64-linux-gnu/libpcl_recognition.so
> -- Found PCL_STEREO: /usr/lib/x86_64-linux-gnu/libpcl_stereo.so
> -- Found PCL_APPS: /usr/lib/x86_64-linux-gnu/libpcl_apps.so
> -- Found PCL_IN_HAND_SCANNER: /usr/include/pcl-1.8
> -- Found PCL_MODELER: /usr/include/pcl-1.8
> -- Found PCL_POINT_CLOUD_EDITOR: /usr/include/pcl-1.8
> -- Found PCL_OUTOFCORE: /usr/lib/x86_64-linux-gnu/libpcl_outofcore.so
> -- Found PCL_PEOPLE: /usr/lib/x86_64-linux-gnu/libpcl_people.so
> -- Boost version: 1.65.1
> -- Found the following Boost libraries:
> -- program_options
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/xlla/git/cpu_tsdf/build
> Scanning dependencies of target get_intrinsics
> Scanning dependencies of target cpu_tsdf
> [ 9%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/octree.cpp.o
> [ 18%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o
> [ 27%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/tsdf_interface.cpp.o
> [ 36%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/tsdf_volume_octree.cpp.o
> [ 45%] Building CXX object CMakeFiles/get_intrinsics.dir/src/prog/get_intrinsics.cpp.o
> /home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp: In member function ‘void cpu_tsdf::MarchingCubesTSDFOctree::setInputTSDF(cpu_tsdf::TSDFVolumeOctree::ConstPtr)’:
> /home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:3: error: ‘size_voxel_’ was not declared in this scope
> size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
> ^~~~~~~~~~~
> /home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:3: note: suggested alternative: ‘size_x’
> size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
> ^~~~~~~~~~~
> size_x
> /home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:18: error: ‘upper_boundary_’ was not declared in this scope
> size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
> ^~~~~~~~~~~~~~~
> /home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:36: error: ‘lower_boundary_’ was not declared in this scope
> size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
> ^~~~~~~~~~~~~~~
> In file included from /home/xlla/git/cpu_tsdf/src/prog/get_intrinsics.cpp:42:0:
> /usr/include/pcl-1.8/pcl/visualization/cloud_viewer.h:202:14: warning: ‘template class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
> std::auto_ptr<CloudViewer_impl> impl_;
> ^~~~~~~~
> In file included from /usr/include/c++/7/memory:80:0,
> from /usr/include/boost/config/no_tr1/memory.hpp:21,
> from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
> from /usr/include/boost/shared_ptr.hpp:17,
> from /usr/include/pcl-1.8/pcl/correspondence.h:45,
> from /usr/include/pcl-1.8/pcl/visualization/pcl_visualizer.h:42,
> from /usr/include/pcl-1.8/pcl/visualization/cloud_viewer.h:39,
> from /home/xlla/git/cpu_tsdf/src/prog/get_intrinsics.cpp:42:
> /usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
> template class auto_ptr;
> ^~~~~~~~
> CMakeFiles/cpu_tsdf.dir/build.make:134: recipe for target 'CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o' failed
> make[2]: *** [CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/cpu_tsdf.dir/all' failed
> make[1]: *** [CMakeFiles/cpu_tsdf.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> [ 54%] Linking CXX executable get_intrinsics
> [ 54%] Built target get_intrinsics
> Makefile:129: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> if I comment that line, ... size_voxel_ ..., then it built.

Do you solve this now? I also meet with this question

**Comment by sumr4693** [comment]
> > when I try build the code, the follow error occur:
> > mkdir build && cd build && cmake .. && make -j8
> > -- The C compiler identification is GNU 7.4.0
> > -- The CXX compiler identification is GNU 7.4.0
> > -- Check for working C compiler: /usr/bin/cc
> > -- Check for working C compiler: /usr/bin/cc -- works
> > -- Detecting C compiler ABI info
> > -- Detecting C compiler ABI info - done
> > -- Detecting C compile features
> > -- Detecting C compile features - done
> > -- Check for working CXX compiler: /usr/bin/c++
> > -- Check for working CXX compiler: /usr/bin/c++ -- works
> > -- Detecting CXX compiler ABI info
> > -- Detecting CXX compiler ABI info - done
> > -- Detecting CXX compile features
> > -- Detecting CXX compile features - done
> > -- Found OpenMP_C: -fopenmp (found version "4.5")
> > -- Found OpenMP_CXX: -fopenmp (found version "4.5")
> > -- Found OpenMP: TRUE (found version "4.5")
> > -- Checking for module 'eigen3'
> > -- Found eigen3, version 3.3.4
> > -- Found eigen: /usr/include/eigen3
> > -- Checking for module 'libopenni'
> > -- Found libopenni, version 1.5.4.0
> > -- Found openni: /usr/lib/libOpenNI.so
> > -- Found libusb-1.0: /usr/include
> > -- Checking for module 'flann'
> > -- Found flann, version 1.9.1
> > -- Found Flann: /usr/lib/x86_64-linux-gnu/libflann_cpp_s.a
> > -- Found qhull: /usr/lib/x86_64-linux-gnu/libqhull.so
> > -- Found PCL_COMMON: /usr/lib/x86_64-linux-gnu/libpcl_common.so
> > -- Found PCL_OCTREE: /usr/lib/x86_64-linux-gnu/libpcl_octree.so
> > -- Found PCL_IO: /usr/lib/x86_64-linux-gnu/libpcl_io.so
> > -- Found PCL_KDTREE: /usr/lib/x86_64-linux-gnu/libpcl_kdtree.so
> > -- Found PCL_SEARCH: /usr/lib/x86_64-linux-gnu/libpcl_search.so
> > -- Found PCL_SAMPLE_CONSENSUS: /usr/lib/x86_64-linux-gnu/libpcl_sample_consensus.so
> > -- Found PCL_FILTERS: /usr/lib/x86_64-linux-gnu/libpcl_filters.so
> > -- Found PCL_2D: /usr/include/pcl-1.8
> > -- Found PCL_GEOMETRY: /usr/include/pcl-1.8
> > -- Found PCL_FEATURES: /usr/lib/x86_64-linux-gnu/libpcl_features.so
> > -- Found PCL_ML: /usr/lib/x86_64-linux-gnu/libpcl_ml.so
> > -- Found PCL_SEGMENTATION: /usr/lib/x86_64-linux-gnu/libpcl_segmentation.so
> > -- Found PCL_VISUALIZATION: /usr/lib/x86_64-linux-gnu/libpcl_visualization.so
> > -- Found PCL_SURFACE: /usr/lib/x86_64-linux-gnu/libpcl_surface.so
> > -- Found PCL_REGISTRATION: /usr/lib/x86_64-linux-gnu/libpcl_registration.so
> > -- Found PCL_KEYPOINTS: /usr/lib/x86_64-linux-gnu/libpcl_keypoints.so
> > -- Found PCL_TRACKING: /usr/lib/x86_64-linux-gnu/libpcl_tracking.so
> > -- Found PCL_RECOGNITION: /usr/lib/x86_64-linux-gnu/libpcl_recognition.so
> > -- Found PCL_STEREO: /usr/lib/x86_64-linux-gnu/libpcl_stereo.so
> > -- Found PCL_APPS: /usr/lib/x86_64-linux-gnu/libpcl_apps.so
> > -- Found PCL_IN_HAND_SCANNER: /usr/include/pcl-1.8
> > -- Found PCL_MODELER: /usr/include/pcl-1.8
> > -- Found PCL_POINT_CLOUD_EDITOR: /usr/include/pcl-1.8
> > -- Found PCL_OUTOFCORE: /usr/lib/x86_64-linux-gnu/libpcl_outofcore.so
> > -- Found PCL_PEOPLE: /usr/lib/x86_64-linux-gnu/libpcl_people.so
> > -- Boost version: 1.65.1
> > -- Found the following Boost libraries:
> > -- program_options
> > -- Configuring done
> > -- Generating done
> > -- Build files have been written to: /home/xlla/git/cpu_tsdf/build
> > Scanning dependencies of target get_intrinsics
> > Scanning dependencies of target cpu_tsdf
> > [ 9%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/octree.cpp.o
> > [ 18%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o
> > [ 27%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/tsdf_interface.cpp.o
> > [ 36%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/tsdf_volume_octree.cpp.o
> > [ 45%] Building CXX object CMakeFiles/get_intrinsics.dir/src/prog/get_intrinsics.cpp.o
> > /home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp: In member function ‘void cpu_tsdf::MarchingCubesTSDFOctree::setInputTSDF(cpu_tsdf::TSDFVolumeOctree::ConstPtr)’:
> > /home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:3: error: ‘size_voxel_’ was not declared in this scope
> > size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
> > ^~~~~~~~~~~
> > /home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:3: note: suggested alternative: ‘size_x’
> > size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
> > ^~~~~~~~~~~
> > size_x
> > /home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:18: error: ‘upper_boundary_’ was not declared in this scope
> > size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
> > ^~~~~~~~~~~~~~~
> > /home/xlla/git/cpu_tsdf/src/lib/marching_cubes_tsdf_octree.cpp:82:36: error: ‘lower_boundary_’ was not declared in this scope
> > size_voxel_ = (upper_boundary_ - lower_boundary_)* Eigen::Array3f(res_x_, res_y_, res_z_).inverse();
> > ^~~~~~~~~~~~~~~
> > In file included from /home/xlla/git/cpu_tsdf/src/prog/get_intrinsics.cpp:42:0:
> > /usr/include/pcl-1.8/pcl/visualization/cloud_viewer.h:202:14: warning: ‘template class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
> > std::auto_ptr<CloudViewer_impl> impl_;
> > ^~~~~~~~
> > In file included from /usr/include/c++/7/memory:80:0,
> > from /usr/include/boost/config/no_tr1/memory.hpp:21,
> > from /usr/include/boost/smart_ptr/shared_ptr.hpp:23,
> > from /usr/include/boost/shared_ptr.hpp:17,
> > from /usr/include/pcl-1.8/pcl/correspondence.h:45,
> > from /usr/include/pcl-1.8/pcl/visualization/pcl_visualizer.h:42,
> > from /usr/include/pcl-1.8/pcl/visualization/cloud_viewer.h:39,
> > from /home/xlla/git/cpu_tsdf/src/prog/get_intrinsics.cpp:42:
> > /usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
> > template class auto_ptr;
> > ^~~~~~~~
> > CMakeFiles/cpu_tsdf.dir/build.make:134: recipe for target 'CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o' failed
> > make[2]: *** [CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o] Error 1
> > make[2]: *** Waiting for unfinished jobs....
> > CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/cpu_tsdf.dir/all' failed
> > make[1]: *** [CMakeFiles/cpu_tsdf.dir/all] Error 2
> > make[1]: *** Waiting for unfinished jobs....
> > [ 54%] Linking CXX executable get_intrinsics
> > [ 54%] Built target get_intrinsics
> > Makefile:129: recipe for target 'all' failed
> > make: *** [all] Error 2
> > if I comment that line, ... size_voxel_ ..., then it built.
> 
> Do you solve this now? I also meet with this question

I just commented that line, and I could build the code without any problem.

**Comment by HuangTY96** [comment]
same question, but if I comment that line, does it affect the whole project?

**Comment by sumr4693** [comment]
> same question, but if I comment that line, does it affect the whole project?

I don't think so.. It worked after that.

**Comment by GITSHOHOKU** [comment]
```
Eigen::Array3f upper_boundary_;
  Eigen::Array3f lower_boundary_;
  Eigen::Array3f size_voxel_;
```
adding code above to cpu_tsdf::MarchingCubesTSDFOctree::setInputTSDF  which is the first function  in  marching_cubes_tsdf_octree.cpp can solve this problem. hope this can help you

**Comment by sdmiller** [comment]
Once again, I must apologize for taking so long to respond to this! I've built this project against PCL 1.10 - 1.13 and it has worked fine with no modifications. I

'm afraid I'm no longer able to compile PCL 1.8 to test this fix, as it relies on a fairly ancient version of boost.  For now, I'm upping the dependency to 1.10: but if you or anyone else are willing to support 1.8 or 1.9, I'm happy to follow your lead.
