### ISSUE TITLE
is the hpp file:tsdf_volume_octree.hpp any useful in this project?

### ISSUE THREAD

**Issue by GuangfuWang** [sdmiller/cpu_tsdf#46]
i am a rookie of PCL and these other libs involved and find this project is quite interesting. But when i look into this source code, i am confused by this tsdf_volume_octree.hpp file in the folder of impl. The main confusion is that i did NOT find any usage of this file in this project, so what is the purpose of this hpp file?

**Comment by sdmiller** [comment]
Hi @GuangfuWang ,

I'm so sorry for taking so long to get back to you. Apparently I hadn't been checking notifications on this repo.

The .hpp file is indeed used. You can find it included in the primary header file (tsdf_volume_octree.h). This is an annoying, but relatively standard, pattern. It stems from the fact that templatized code can't be precompiled in a source file (it needs to be visible in the header), but we still want to keep our header files clean. The compromise is to put the implementation of a template function in an "hpp" file. If you check out the PCL codebase, you'll find that I stole this from them :)
