### ISSUE TITLE
Core dumped when I run integrate 

### ISSUE THREAD

**Issue by Junkai-Liu** [sdmiller/cpu_tsdf#51]
When I run integrate executable file , as follows:
./integrate --in ../sample_data/ --out ../output_data/
The output error is :
Found PCD files with prefix: ../sample_data/cloud_, poses with prefix: ../sample_data/pose_ poses
Reading in ascii pose files
Segmentation fault (core dumped)

**Comment by sdmiller** [comment]
Hi @Junkai-Liu, apologies that it took this long to respond: This codebase is quite old, and I've neglected it for a while. If you are still having a segmentation fault, please open a new issue with the OS and PCL versions you are using, and I would be happy to try and diagnose it.
