### ISSUE TITLE
rtabmap+cputsdf+pcl1.8.1

### ISSUE THREAD

**Issue by HuangTY96** [sdmiller/cpu_tsdf#52]
when I build cputsdf, cmake .. & make, and there is an error.
[ 18%] Built target get_intrinsics
[ 27%] Building CXX object CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o
In file included from /home/hty/Downloads/cpu_tsdf-master/include/cpu_tsdf/marching_cubes_tsdf_octree.h:46:0,
                 from /home/hty/Downloads/cpu_tsdf-master/src/lib/marching_cubes_tsdf_octree.cpp:41:
/usr/include/pcl-1.8/pcl/surface/impl/marching_cubes.hpp: In member function ‘virtual void pcl::MarchingCubes<PointNT>::performReconstruction(pcl::PointCloud<PointT>&, std::vector<pcl::Vertices>&)’:
/usr/include/pcl-1.8/pcl/surface/impl/marching_cubes.hpp:298:3: error: ‘size_voxel_’ was not declared in this scope
   size_voxel_ = (upper_boundary_ - lower_boundary_) * Eigen::Array3f (res_x_, res_y_, res_z_).inverse ();
   ^~~~~~~~~~~
/usr/include/pcl-1.8/pcl/surface/impl/marching_cubes.hpp:298:18: error: ‘upper_boundary_’ was not declared in this scope
   size_voxel_ = (upper_boundary_ - lower_boundary_) * Eigen::Array3f (res_x_, res_y_, res_z_).inverse ();
                  ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/surface/impl/marching_cubes.hpp:298:36: error: ‘lower_boundary_’ was not declared in this scope
   size_voxel_ = (upper_boundary_ - lower_boundary_) * Eigen::Array3f (res_x_, res_y_, res_z_).inverse ();
                                    ^~~~~~~~~~~~~~~
CMakeFiles/cpu_tsdf.dir/build.make:134: recipe for target 'CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o' failed
make[2]: *** [CMakeFiles/cpu_tsdf.dir/src/lib/marching_cubes_tsdf_octree.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/cpu_tsdf.dir/all' failed
make[1]: *** [CMakeFiles/cpu_tsdf.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

and then I comment that line, the error will be solved, but when I build rtabmap with cputsdf, it cannot be used with cputsdf meshing, there are no polygon. 
so, I think this error should not be solved in this way, but how to solve it?

**Comment by sdmiller** [comment]
Hi Huang,

Could you explain a bit more about the code you're depending on here? When I check [source code](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.8.1/surface/include/pcl/surface/impl/marching_cubes.hpp) for pcl-1.8.1, I don't see the line that is throwing an error (same for pcl-1.8.0 for that matter). In fact, I can't seem to find these variables in the codebase at all.

I do find them, however, [on pcl-1.9.0](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.9.0/surface/include/pcl/surface/impl/marching_cubes.hpp#L245). So something seems fishy to me here.

**Comment by HuangTY96** [comment]
> Hi Huang,
> 
> Could you explain a bit more about the code you're depending on here? When I check [source code](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.8.1/surface/include/pcl/surface/impl/marching_cubes.hpp) for pcl-1.8.1, I don't see the line that is throwing an error (same for pcl-1.8.0 for that matter). In fact, I can't seem to find these variables in the codebase at all.
> 
> I do find them, however, [on pcl-1.9.0](https://github.com/PointCloudLibrary/pcl/blob/pcl-1.9.0/surface/include/pcl/surface/impl/marching_cubes.hpp#L245). So something seems fishy to me here.

Yes, I found that too, thanks a lot!
